spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths:
        - src/main/resources/static
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
      cache:
        period: 0
      chain:
        cache: false
