spring:
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms
      log-condition: delta-time
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
      cache:
        period: 0
      chain:
        cache: false
