SET NAMES utf8mb4;

SET @c = CAST(UNHEX('E5A4A7E585B3E58DA1E6A8A1E5BC8FE58886E7BB84') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_mode_group` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E5A4A7E585B3E58DA1') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_chapter` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E5B08FE585B3E58DA1E7BB84') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_stage_group` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E5B08FE585B3E58DA1') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_stage` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('505645E4B8BBE8A792') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_hero` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E6B8B8E6888FE789A9E59381') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_item` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E680AAE789A9E68E89E890BDE9858DE7BDAE') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_monster_drop` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E78EA9E5AEB6E4BB93E5BA93') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_warehouse` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E4BB93E5BA93E789A9E59381') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_inventory` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E789A9E59381E58F98E58AA8E697A5E5BF97') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_item_log` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E680AAE789A9') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_monster` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E5B08FE585B3E58DA1E6B3A2E6ACA1') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_wave` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E6B3A2E6ACA1E680AAE789A9') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_game_wave_monster` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E8BDAEE692ADE6A8AAE5B985') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_banner` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E69687E7ABA0E8A1A8') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_article` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E794A8E688B7E8A1A8') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_member` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E794A8E688B74B5943E8AEA4E8AF81') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_member_kyc` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E6B8B8E6888FE8B4A7E5B881E4BAA4E69893E8AEB0E5BD95') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_money_record` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E7A7AFE58886E694AFE4BB98E8AEA2E58D95') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_point_pay_order` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E7A7AFE58886E992B1E58C85') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_point_wallet` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('57656233E5B881E7A78DE9858DE7BDAE') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_web3_coin` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('57656233E58585E580BCE8AEB0E5BD95') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_web3_recharge` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('57656233E993BEE4B88AE79B91E590AC') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_web3_run_watch` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('57656233E992B1E58C85') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_web3_wallet` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('57656233E68F90E78EB0E8AEB0E5BD95') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `app_web3_withdraw` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E59FBAE7A180E695B0E68DAEE8A1A8') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_base_table` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E5A49AE8AFADE8A880E9858DE7BDAE') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_more_lang` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('E7B3BBE7BB9FE58F82E695B0') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_super_param` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('4C3320E696B9E6B395E689A7E8A18CE697A5E5BF97') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_log_method` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('4C3120E8AFB7E6B182E59FBAE7A180E697A5E5BF97') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_log_request` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('4C3220E8AFB7E6B182E695B0E68DAEE58F98E69BB4E697A5E5BF97') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_log_request_detail` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('4C3520E7ACACE4B889E696B9E59B9EE8B083E697A5E5BF97') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_log_third_callback` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @c = CAST(UNHEX('4C3420E4B889E696B9E4BAA4E4BA92E697A5E5BF97') AS CHAR CHARACTER SET utf8mb4);
SET @sql = CONCAT('ALTER TABLE `wx_log_third_party` COMMENT = ', QUOTE(@c));
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

